version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: container-viewer-dev
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    environment:
      - GO_ENV=development
    labels:
      - com.dynamic-port-mapper.has-dynamic-ports=true
